name: My Test Action
description: My Test Action CI-CD

# Inputs
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'default value'

  message2:
    description: 'The message to print 2'
    required: false
    default: 'default value2'

runs:
  using: 'composite'
  
  steps:
    - name: Print messages
      shell: bash
      run: |
        "Message: ${{ inputs.message }}!"
        echo "Message2: ${{ inputs.message2 }}!"